sonar.projectKey=josemoura212_fc-sonar-challenge
sonar.organization=josemoura212

sonar.projectName=fc-sonar-challenge
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
